name: 'Continuous Integration'

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build node.js ${{ matrix.version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ['14', '16']
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.version }}

            - name: Install
              run: yarn

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test
